name       : rtl-sdr
version    : 0.7.0
release    : 2
source     :
    - https://github.com/librtlsdr/librtlsdr/archive/v0.7.0.tar.gz : f6ff07b64be2aa9d47257ae55ed2aaa3d068e31b834f7c674bd136163613ce85
license    : GPL-2.0
component  : multimedia.library
summary    : Software to turn the RTL2832U into an SDR
description: |
    rtl-sdr can turns your Realtek RTL2832 based DVB-T dongle into a SDR receiver.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %cmake . -DDETACH_KERNEL_DRIVER=ON
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 rtl-sdr.rules $installdir/%libdir%/udev/rules.d/10-rtl-sdr.rules

    rm $installdir/usr/lib/*.a
